/* tslint:disable:max-line-length */
import { FuseNavigationItem } from "@fuse/components/navigation";
import { random } from "lodash";

export const defaultNavigation: FuseNavigationItem[] = [
	{
		id: "landing",
		title: "Home",
		type: "basic",
		link: "/landing",
		icon: "heroicons_outline:home",
	},
	//ACM
	{
		id: "acm",
		title: "ACM",
		type: "collapsable",
		icon: "heroicons_outline:chip",

		children: [
			{
				id: "dashboard",
				title: "Dashboard",
				type: "basic",
				link: "/acm/acmdashboard",
				icon: "heroicons_outline:view-grid",
			},
			{
				id: "rule-book",
				title: "Rule Book",
				type: "collapsable",
				icon: "heroicons_outline:speakerphone",
				children: [
					{
						id: "rules",
						title: "Rules",
						type: "basic",
						link: "/acm/rule-book/rules",
						icon: "heroicons_outline:document-text",
					},
					{
						id: "risk",
						icon: "heroicons_outline:shield-exclamation",
						title: "Risk",
						type: "basic",
						link: "/acm/rule-book/risk",
					},
					{
						id: "variant",
						icon: "heroicons_outline:newspaper",
						title: "Variant",
						type: "collapsable",
						children: [
							{
								id: "risk",
								title: "Risk",
								type: "basic",
								icon: "heroicons_outline:folder-open",
								link: "/acm/rule-book/variant/risk",
							},
							{
								id: "rules",
								title: "Rules",
								icon: "heroicons_outline:folder-open",
								type: "basic",
								link: "/acm/rule-book/variant/rules",
							},
						],
					},
					{
						id: "import",
						icon: "heroicons_outline:save",
						title: "Import",
						type: "collapsable",
						children: [
							{
								id: "rules",
								title: "Import Rules",
								type: "basic",
								icon: "heroicons_outline:plus-sm",
								link: "/acm/rule-book/import/rules",
							},
							{
								id: "risk",
								title: "Import Risk",
								type: "basic",
								icon: "heroicons_outline:plus-sm",
								link: "/acm/rule-book/import/risk",
							},
						],
					},
					{
						id: "audit-logs",
						title: "Audit Logs",
						icon: "heroicons_outline:download",
						type: "collapsable",
						children: [
							{
								id: "rules",
								title: "Rules",
								icon: "heroicons_outline:folder-open",
								type: "basic",
								link: "/acm/rule-book/audit-logs/rules",
							},
							{
								id: "risk",
								title: "Risk",
								icon: "heroicons_outline:folder-open",
								type: "basic",
								link: "/acm/rule-book/audit-logs/risk",
							},
						],
					},
				],
			},
			{
				id: "master-data",
				title: "Master Data",
				type: "collapsable",
				icon: "heroicons_outline:database",
				children: [
					{
						id: "mitigations",
						title: "Mitigations",
						type: "collapsable",
						icon: "heroicons_outline:bookmark-alt",
						children: [
							{
								id: "mc-control",
								title: "MC Control",
								icon: "heroicons_outline:briefcase",
								type: "basic",
								link: "/acm/master-data/mitigations/mc-control",
							},
							{
								id: "upload",
								title: "Upload",
								icon: "heroicons_outline:cloud-upload",
								type: "basic",
								link: "/acm/master-data/mitigations/upload",
							},
						],
					},
					{
						id: "acm-owners",
						title: "ACM Owners",
						type: "basic",
						link: "/acm/master-data/acm-owners",
						icon: "heroicons_outline:archive",
					},
					{
						id: "rule-type",
						title: "Rule Type",
						type: "basic",
						link: "/acm/master-data/rule-type",
						icon: "heroicons_outline:document-text",
					},
					{
						id: "risk-type",
						title: "Risk Type",
						type: "basic",
						icon: "heroicons_outline:document-text",
						link: "/acm/master-data/risk-type",
					},
					{
						id: "business-process",
						title: "Business Processes",
						icon: "heroicons_outline:presentation-chart-line",
						type: "basic",
						link: "/acm/master-data/business-processes",
					},
					{
						id: "business-sub-process",
						title: "Business Sub Processes",
						type: "basic",
						icon: "heroicons_outline:presentation-chart-bar",
						link: "/acm/master-data/business-sub-processes",
					},
					{
						id: "org-field",
						title: "Org Field",
						icon: "heroicons_outline:globe-alt",
						type: "collapsable",
						children: [
							{
								id: "org-fields",
								title: "ORG Fields",
								type: "basic",
								icon: "heroicons_outline:plus-circle",
								link: "/acm/master-data/org-field/org-fields",
							},
							{
								id: "org-fields",
								title: "Download",
								type: "basic",
								icon: "heroicons_outline:download",
								link: "/acm/master-data/org-field/download",
							},
							{
								id: "org-fields",
								title: "Upload",
								type: "basic",
								icon: "heroicons_outline:cloud-upload",
								link: "/acm/master-data/org-field/upload",
							},
							{
								id: "org-names",
								title: "ORG Names",
								type: "basic",
								icon: "heroicons_outline:plus-circle",
								link: "/acm/master-data/org-field/org-names",
							},
							{
								id: "org-names",
								title: "ORG Names Variant",
								type: "basic",
								icon: "heroicons_outline:plus-circle",
								link: "/acm/master-data/org-field/org-names-variant",
							},
						],
					},
				],
			},
			{
				id: "rem",
				title: "REM",
				icon: "heroicons_outline:folder-open",
				type: "collapsable",
				children: [
					{
						id: "rem-config",
						title: "REM Config",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/acm/rem/rem-config",
					},
					{
						id: "risk-schedule",
						title: "Risk Schedule",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/acm/rem/risk-schedule",
					},
					{
						id: "tcode-sync",
						title: "Tcode Sync",
						type: "basic",
						link: "/acm/rem/tcode-sync",
						icon: "heroicons_outline:plus",
					},
				],
			},
			{
				id: "risk-analysis",
				title: "Risk Analysis",
				icon: "heroicons_outline:eye",
				type: "collapsable",
				children: [
					{
						id: "online",
						title: "Online",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/online/" + random(1, 100000),
					},
					{
						id: "offline",
						title: "Offline",
						icon: "heroicons_outline:folder-open",
						type: "collapsable",
						children: [
							{
								id: "import",
								icon: "heroicons_outline:folder-download",
								title: "Import",
								type: "basic",
								link: "/acm/risk-analysis/offline/import",
							},
							{
								id: "user-browser",
								title: "User Browser",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/user-browser",
							},
							{
								id: "user-variant",
								title: "User Variant",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/user-variant",
							},
							{
								id: "sod-analysis",
								title: "SoD Analysis",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/sod-analysis",
							},
							{
								id: "tasks",
								title: "Tasks",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/tasks",
							},
						],
					},
					{
						id: "simulation",
						title: "Simulation",
						icon: "heroicons_outline:folder-open",
						type: "collapsable",
						children: [
							{
								id: "online",
								title: "Online",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/simulation/online",
							},
							{
								id: "offline",
								title: "Offilne",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/simulation/offline",
							},
						],
					},
					{
						id: "position-id",
						title: "Position Id",
						icon: "heroicons_outline:folder-open",
						type: "collapsable",
						children: [
							{
								id: "analyisis",
								title: "Analysis",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/position-id/analyisis",
							},
							{
								id: "Logs",
								title: "logs",
								type: "basic",
								icon: "heroicons_outline:folder-add",
								link: "/acm/risk-analysis/position-id/logs",
							},
						],
					},
					{
						id: "impact-analsis",
						title: "Impact Analysis",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/impact-analysis",
					},
					{
						id: "cross-system-analysis",
						title: "Cross System Online",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/cross-system-analysis-online/" + random(1, 100000),
					},
					{
						id: "cross-system-analysis1",
						icon: "heroicons_outline:folder-open",
						title: "Cross System Offline",
						type: "basic",
						link: "/acm/risk-analysis/cross-system-analysis1-offline/" + random(1, 100000),
					},
					{
						id: "dashboard",
						title: "Dashboard",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/dashboard",
					},
					{
						id: "sfAnalysis",
						title: "Non-ABAP",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/sfAnalysis/" + random(1, 100000),
					},
				],
			},
			{
				id: "reports",
				title: "Reports",
				icon: "heroicons_outline:clipboard-list",
				type: "collapsable",
				children: [
					{
						id: "sod-results",
						title: "SoD Results",
						type: "basic",
						icon: "heroicons_outline:clipboard-check",
						link: "/acm/reports/sod-results",
					},
					{
						id: "cross-system-analysis",
						title: "Cross Analysis Results",
						type: "basic",
						link: "/acm/reports/cross-system-analysis",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "org-analysis-dashboard",
						title: "ORG Analysis Dashboard",
						type: "basic",
						link: "/acm/reports/org-analysis-dashboard",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "org-level-analysis",
						title: "ORG Analysis Results",
						type: "basic",
						link: "/acm/reports/org-level-analysis",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "org-report",
						title: "ORG Report",
						type: "basic",
						link: "/acm/reports/org-report",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "mitigation-report",
						title: "Mitigation Report",
						type: "basic",
						link: "/acm/reports/mitigation-report",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "risk-report",
						title: "Risk Report",
						type: "basic",
						link: "/acm/reports/risk-report",
						icon: "heroicons_outline:clipboard-check",
					},
					// {
					//   id: 'user-report',
					//   title: 'User Report',
					//   type: 'basic',
					//   link: '/acm/reports/user-report',
					//   icon: 'heroicons_outline:clipboard-check',
					// },
					{
						id: "risk-execution",
						title: "Risk Execution",
						type: "basic",
						link: "/acm/reports/risk-execution",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "rule-execution",
						title: "Rule Execution",
						type: "basic",
						link: "/acm/reports/rule-execution",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "tcode-execution",
						title: "Tcode Execution",
						type: "basic",
						link: "/acm/reports/tcode-execution",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "risk-exe-execution",
						title: "Risk Exe Summary",
						type: "basic",
						link: "/acm/reports/risk-exe-summary",
						icon: "heroicons_outline:clipboard-check",
					},

					{
						id: "rem-dashboard",
						title: "REM Dashboard",
						type: "basic",
						link: "/acm/reports/rem-dashboard",
						icon: "heroicons_outline:clipboard-check",
					},
				],
			},
		],
	},
	//PAM
	{
		id: "pam",
		title: "PAM",
		type: "collapsable",
		icon: "heroicons_outline:office-building",
		children: [
			{
				id: "pam-dashboard",
				title: "PAM Dashboard",
				icon: "heroicons_outline:template",
				type: "basic",
				link: "/pam/pam-dashboard/dashboard",
			},
			{
				id: "requests",
				title: "Requests",
				icon: "heroicons_outline:search-circle",
				type: "collapsable",
				children: [
					{
						id: "my-requests",
						title: "My Requests",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/pam/requests/my-requests",
					},
					{
						id: "my-approvals",
						title: "My Approvals",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/requests/my-approvals",
					},
					{
						id: "my-reviews",
						title: "My Reviews",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/requests/my-reviews",
					},
				],
			},
			{
				id: "reports",
				title: "Reports",
				icon: "heroicons_outline:clipboard-check",
				type: "collapsable",
				children: [
					{
						id: "master-data",
						title: "Master Data",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/reports/master-data",
					},
					{
						id: "request-pivot",
						title: "Request Pivot",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/reports/request-pivot",
					},
					{
						id: "all-requests",
						title: "All Requests",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/reports/all-requests",
					},
					{
						id: "audit-logs",
						title: "Audit Logs",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/reports/audit-logs",
					},
				],
			},
			{
				id: "setup",
				title: "Setup",
				icon: "heroicons_outline:cog",
				type: "collapsable",
				children: [
					{
						id: "privileges",
						icon: "heroicons_outline:plus",
						title: "Privileges",
						type: "basic",
						link: "/pam/setup/privileges",
					},
					{
						id: "review-rule",
						title: "Review Rule",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/setup/review-rule",
					},
					{
						id: "reasons",
						title: "Reasons",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/pam/setup/reasons",
					},
					{
						id: "synchronize",
						title: "Synchronize",
						icon: "heroicons_outline:refresh",
						type: "collapsable",
						link: "/pam/setup/synchronize",
						children: [
							{
								id: "schedulers",
								title: "Schedulers",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/pam/setup/synchronize/schedulers",
							},
							{
								id: "jobs",
								title: "Jobs",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/pam/setup/synchronize/jobs",
							},
						],
					},
				],
			},
		],
	},
	//CAM
	{
		id: "cam",
		title: "CAM",
		type: "collapsable",
		icon: "heroicons_outline:briefcase",
		children: [
			{
				id: "dashboard",
				icon: "heroicons_outline:presentation-chart-line",
				title: "CAM Dashboard",
				type: "basic",
				link: "/cam/dashboard",
			},
			{
				id: "requests",
				title: "Requests",
				icon: "heroicons_outline:cursor-click",
				type: "collapsable",
				children: [
					{
						id: "single",
						title: "Single",
						icon: "heroicons_outline:save",
						type: "collapsable",
						children: [
							{
								id: "Create",
								title: "Create",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/create",
							},
							{
								id: "Change",
								title: "Change",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/change",
							},
							{
								id: "lock/unlock",
								title: "Lock / Unlock",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/lock-unlock",
							},
							{
								id: "Reset-Password",
								title: "Reset Password",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/reset-password",
							},
							{
								id: "Delete",
								title: "Delete",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/delete",
							},
						],
					},
					{
						id: "multiple",
						title: "Multiple",
						icon: "heroicons_outline:save-as",
						type: "collapsable",
						children: [
							{
								id: "Create",
								title: "Create",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/multiple/create",
							},
							{
								id: "Change",
								title: "Change",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/multiple/change",
							},
							{
								id: "lock/unlock",
								title: "Lock / Unlock",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/multiple/lock-unlock",
							},
							{
								id: "Reset-Password",
								title: "Reset Password",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/multiple/reset-password",
							},
							{
								id: "Delete",
								title: "Delete",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/multiple/delete",
							},
						],
					},
					{
						id: "non-abap",
						title: "Non-ABAP",
						icon: "heroicons_outline:search",
						type: "collapsable",
						children: [
							{
								id: "successFactors",
								title: "Success Factors",
								icon: "heroicons_outline:plus-circle",
								type: "collapsable",
								children: [
									{
										id: "users",
										title: "Users",
										icon: "heroicons_outline:plus",
										type: "basic",
										link: "/cam/non-apap/success-factors/users",
									},
									{
										id: "group",
										title: "Groups",
										icon: "heroicons_outline:plus",
										type: "basic",
										link: "/cam/non-apap/success-factors/groups",
									},
								],
							},
							{
								id: "hanaDBUsers",
								title: "HANA DB Users",
								icon: "heroicons_outline:plus-circle",
								type: "basic",
								link: "/cam/non-apap/hanadb",
							},
							{
								id: "BOBJUsers",
								title: "BOBJ Users",
								icon: "heroicons_outline:plus-circle",
								type: "basic",
								link: "/cam/bobj-users",
							},
						],
					},
				],
			},
			{
				id: "self-service",
				icon: "heroicons_outline:phone-outgoing",
				title: "Self Service",
				type: "collapsable",
				link: "/central-users/central-users-db/dashboard",
				children: [
					{
						id: "unlock",
						title: "Unlock",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/self-service/unlock",
					},
					{
						id: "reset-password",
						title: "Reset Password",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/self-service/reset-passwords",
					},
					{
						id: "requests",
						title: "Requests",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/self-service/requests",
					},
				],
			},
			{
				id: "workflow",
				title: "Workflow",
				type: "collapsable",
				icon: "heroicons_outline:briefcase",
				children: [
					{
						id: "my-requests",
						title: "My Requests",
						type: "basic",
						link: "/cam/workflow/requests",
						icon: "heroicons_outline:plus",
					},
					{
						id: "my-approvals",
						title: "My approvals",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/workflow/approvals",
					},
					{
						id: "node",
						title: "Node",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/workflow/node",
					},
					{
						id: "workflow",
						title: "Workflow",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/workflow/workflow",
					},
					{
						id: "all-requests",
						title: "All Requests",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/workflow/all-requests",
					},
					{
						id: "audit-logs",
						title: "Audit Logs",
						icon: "heroicons_outline:search-circle",
						type: "collapsable",
						children: [
							{
								id: "workflow",
								title: "Workflow",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/workflow/audit-logs/workflow",
							},
							{
								id: "node",
								title: "Node",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/workflow/audit-logs/node",
							},
							{
								id: "delegation",
								title: "Delegation",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/workflow/audit-logs/delegation",
							},
						],
					},
				],
			},
			{
				id: "arc",
				icon: "heroicons_outline:newspaper",
				title: "ARC",
				type: "collapsable",
				children: [
					{
						id: "arc-job",
						title: "ARC Job",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/arc/arc-job",
					},
					{
						id: "review-jobs",
						title: "Review Jobs",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/arc/review-job",
					},
					{
						id: "user-report",
						title: "User Report",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/arc/user-report",
					},
				],
			},
			{
				id: "settings",
				title: "Settings",
				icon: "heroicons_outline:cog",
				type: "collapsable",
				children: [
					{
						id: "sap-system",
						title: "SAP System",
						type: "basic",
						link: "/cam/settings/sap-system",
						icon: "heroicons_outline:plus",
					},
					{
						id: "user-restrictions",
						title: "User Restrictions",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/settings/user-restrictions",
					},
					{
						id: "role-catalogue",
						title: "Role Catalogue",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/settings/role-catalogue",
					},
					{
						id: "request-params",
						title: "Request Params",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/cam/settings/request-params",
					},
					{
						id: "user-provision-field",
						title: "User Provision Field",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/settings/user-provision-field",
					},
					{
						id: "approval-delegation",
						title: "Approval Delegation",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/settings/approval-delegation",
					},
					{
						id: "org-structures",
						title: "Org Structures",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/cam/settings/org-structures",
					},
					{
						id: "role-sync",
						title: "Role Sync",
						icon: "heroicons_outline:refresh",
						type: "collapsable",
						children: [
							{
								id: "schedulers",
								title: "Schedulers",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/settings/role-sync/Schedulers",
							},
							{
								id: "jobs",
								title: "Jobs",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/settings/role-sync/jobs",
							},
						],
					},
					{
						id: "active-directory-sync",
						title: "Active Directory Sync",
						icon: "heroicons_outline:refresh",
						type: "collapsable",
						children: [
							{
								id: "schedulers",
								title: "Schedulers",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/settings/active-directory-sync/Schedulers",
							},
							{
								id: "jobs",
								title: "Jobs",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/cam/settings/active-directory-sync/jobs",
							},
						],
					},
				],
			},
		],
	},
	//ICM
	{
		id: "icm",
		title: "ICM",
		type: "collapsable",
		icon: "heroicons_outline:paper-airplane",
		children: [
			{
				id: "dashboard",
				title: "ICM Dashboard",
				type: "basic",
				icon: "heroicons_outline:presentation-chart-line",
				link: "/icm/dashboard",
			},
			{
				id: "monitor",
				title: "Monitor",
				type: "collapsable",
				icon: "heroicons_outline:eye",
				children: [
					{
						id: "control-monitoring",
						title: "Control Monitoring",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control-monitoring",
					},
					{
						id: "control-overview",
						title: "Control Overview",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control-overview",
					},
					{
						id: "std-control-finance-impact",
						title: "Std Control Finance Impact",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/std-control-finance-impact",
					},
					{
						id: "run-audit-logs",
						title: "Run Audit Logs",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/run-audit-logs",
					},
				],
			},
			{
				id: "controls",
				title: "Controls",
				type: "collapsable",
				icon: "heroicons_outline:terminal",
				children: [
					{
						id: "control",
						title: "Control",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control",
					},
					{
						id: "control-task",
						title: "Control Tasks",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control-task",
					},
					{
						id: "control-deficiency",
						title: "Control Deficiency",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control-deficiency",
					},
					{
						id: "control-pivot-admin",
						title: "Control Pivot Admin",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control-pivot-admin",
					},
					{
						id: "control-report-catalogue",
						title: "Control Report Catalogue",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/icm/control-report-catalogue",
					},
				],
			},
		],
	},

	//Central User
	{
		id: "central-users",
		title: "Central User",
		type: "collapsable",
		icon: "heroicons_outline:user",
		children: [
			{
				id: "central-users-db",
				title: "Central Users",
				icon: "heroicons_outline:user-group",
				type: "collapsable",
				children: [
					{
						id: "dashboard",
						title: "Dashboard",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/central-users-db/dashboard",
					},
					{
						id: "scheduled-task",
						title: "Scheduled Task",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/central-users-db/scheduled-task",
					},
					{
						id: "central-user-report",
						title: "Central User Report",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/central-users-db/central-user-report",
					},
					{
						id: "central-user-pivot-report",
						title: "Central User Pivot Report",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/central-users-db/central-users-dashboard",
					},
					{
						id: "jobs",
						title: "Jobs",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/central-users/central-users-db/jobs",
					},
					{
						id: "inactive-user",
						title: "Inactive User",
						icon: "heroicons_outline:user-group",
						type: "collapsable",
						children: [
							{
								id: "inactive-user-dashboard",
								title: "Inactive User Dashboard",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/central-users/central-users-db/inactive-user/dashboard",
							},
							{
								id: "central-user-lock-parameters",
								title: "Central User Lock Parameters",
								icon: "heroicons_outline:plus",
								type: "basic",
								link: "/central-users/central-users-db/inactive-user/central-user-lock-parameters",
							},
							{
								id: "jobs",
								icon: "heroicons_outline:plus",
								title: "Jobs",
								type: "basic",
								link: "/central-users/central-users-db/inactive-user/jobs",
							},
						],
					},
				],
			},
			{
				id: "system-license-management",
				icon: "heroicons_outline:desktop-computer",
				title: "System License Management ",
				type: "collapsable",
				children: [
					{
						id: "dashboard",
						title: "Dashboard",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/system-license-management/dashboard",
					},
					{
						id: "system-license-info",
						title: "System License Info",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/system-license-management/system-license-info",
					},
					{
						id: "license-rules",
						title: "License Rules",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/system-license-management/license-rules",
					},
					{
						id: "license-indirect-usage",
						title: "License Indirect Usage",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/system-license-management/license-indirect-usage",
					},
					{
						id: "license-management",
						title: "License Management",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/system-license-management/license-management",
					},
					{
						id: "jobs",
						title: "Jobs",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/central-users/system-license-management/jobs",
					},
					{
						id: "pivot-report",
						title: "Pivot Report",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/central-users/system-license-management/pivot-report",
					},
				],
			},
		],
	},
	//Admin
	{
		id: "administration",
		title: "Administration",
		type: "collapsable",
		icon: "heroicons_outline:adjustments",

		children: [
			{
				id: "communication",
				title: "Communication",
				type: "collapsable",
				icon: "heroicons_outline:chat-alt",
				children: [
					{
						id: "email",
						title: "Email",
						type: "collapsable",
						icon: "heroicons_outline:mail",
						children: [
							{
								id: "settings",
								title: "Settings",
								type: "basic",
								link: "/admin/communication/email/settings",
								icon: "heroicons_outline:cog",
							},
							{
								icon: "heroicons_outline:clipboard-list",
								id: "logs",
								title: "Logs",
								type: "basic",
								link: "/admin/communication/email/logs",
							},
						],
					},
					{
						id: "template",
						icon: "heroicons_outline:document-add",
						title: "Template",
						type: "basic",
						link: "/admin/communication/template",
					},
					{
						id: "logo",
						icon: "heroicons_outline:photograph",
						title: "Logo",
						type: "basic",
						link: "/admin/communication/logo",
					},
				],
			},

			{
				id: "authentication",
				title: "Authentication",
				type: "collapsable",
				icon: "heroicons_outline:identification",
				children: [
					{
						id: "ldap",
						icon: "heroicons_outline:template",
						title: "LDAP",
						type: "basic",
						link: "/admin/authentication/ldap",
					},
					{
						id: "loginHistory",
						icon: "heroicons_outline:users",
						title: "Login History",
						type: "basic",
						link: "/admin/authentication/loginEvents",
					},
					{
						id: "Blocked IPs",
						icon: "heroicons_outline:shield-exclamation",
						title: "Blocked IPs",
						type: "basic",
						link: "/admin/authentication/blockedIps",
					},
					{
						id: "users",
						title: "Users",
						type: "basic",
						icon: "heroicons_outline:user-group",
						link: "/admin/authentication/users",
					},
					{
						id: "roles",
						title: "Roles",
						type: "basic",
						icon: "heroicons_outline:puzzle",
						link: "/admin/roles",
					},
					{
						id: "operation",
						title: "Operation",
						type: "basic",
						icon: "heroicons_outline:cog",
						link: "/admin/authentication/operation",
					},
				],
			},
			{
				id: "reporting-units",
				title: "Reporting Units",
				type: "collapsable",
				icon: "heroicons_outline:clipboard-list",
				children: [
					{
						id: "reporting",
						title: "Reporting",
						type: "basic",
						icon: "heroicons_outline:template",
						link: "/admin/reporting-units/reporting",
					},
					{
						id: "sapsystem",
						icon: "heroicons_outline:desktop-computer",
						title: "Systems",
						type: "basic",
						link: "/admin/reporting-units/sap-system",
					},
					{
						id: "database",
						icon: "heroicons_outline:database",
						title: "Database",
						type: "basic",
						link: "/admin/reporting-units/database",
					},
				],
			},
			{
				id: "settings",
				title: "Settings",
				type: "collapsable",
				icon: "heroicons_outline:chart-pie",
				children: [
					{
						id: "application-config",
						title: "Application Config",
						icon: "heroicons_outline:lock-open",
						type: "basic",
						link: "/admin/settings/application-config",
					},
					{
						id: "audit-logs",
						title: "Audit Logs",
						type: "basic",
						icon: "heroicons_outline:briefcase",
						link: "/admin/settings/audit-logs",
					},
				],
			},
			{
				id: "event-viewer",
				title: "Event Viewer",
				type: "collapsable",
				icon: "heroicons_outline:shield-exclamation",
				children: [
					{
						id: "logs",
						title: "Logs",
						type: "basic",
						link: "/admin/event-viewer/logs",
						icon: "heroicons_outline:clipboard-list",
					},
					{
						id: "clear-logs",
						title: "Clear Logs",
						type: "basic",
						link: "/admin/event-viewer/clear-logs",
						icon: "heroicons_outline:x-circle",
					},
				],
			},
			{
				id: "audit-logs",
				title: "Audit Logs",
				type: "basic",
				icon: "heroicons_outline:identification",
				link: "/admin/audit-logs",
			},
			{
				id: "utilities",
				title: "Utilities",
				type: "collapsable",
				icon: "heroicons_outline:chart-pie",
				children: [
					{
						id: "ruleset-conversion",
						title: "Ruleset Conversion",
						icon: "heroicons_outline:search-circle",
						type: "collapsable",
						children: [
							{
								id: "grc-ruleset",
								title: "GRC Ruleset",
								icon: "heroicons_outline:search-circle",
								type: "basic",
								link: "/admin/utilities/ruleset-conversion/grc-ruleset",
							},
							{
								id: "csi-query",
								title: "CSI Query",
								icon: "heroicons_outline:search-circle",
								type: "basic",
								link: "/admin/utilities/ruleset-conversion/csi-query",
							},
						],
					},
				],
			},
			{
				id: "data-sync",
				title: "Data Sync",
				type: "collapsable",
				icon: "heroicons_outline:refresh",
				children: [
					{
						id: "data-extractor",
						icon: "heroicons_outline:server",
						title: "Data Extractor",
						type: "collapsable",
						children: [
							{
								id: "profiles",
								title: "Profiles",
								type: "basic",
								icon: "heroicons_outline:user-circle",
								link: "/admin/data-sync/data-extractor/profiles",
							},
							{
								id: "jobs",
								title: "Jobs",
								icon: "heroicons_outline:briefcase",
								type: "basic",
								link: "/admin/data-sync/data-extractor/jobs",
							},
							{
								id: "scheduler",
								title: "Scheduler",
								type: "basic",
								icon: "heroicons_outline:clock",
								link: "/admin/data-sync/data-extractor/scheduler",
							},
						],
					},
				],
			},
		],
	},
	//General
	{
		id: "general",
		title: "General",
		type: "collapsable",
		icon: "heroicons_outline:chart-pie",
		children: [
			{
				id: "export-results",
				title: "Export Results",
				type: "basic",
				link: "/general/export-results",
				icon: "heroicons_outline:plus",
			},
			{
				id: "user-dashboard",
				title: "User Dashboard",
				type: "basic",
				icon: "heroicons_outline:plus",
				link: "/general/user-dashboard",
			},
			{
				id: "admin-dashboard",
				title: "Admin Dashboard",
				icon: "heroicons_outline:plus",
				type: "basic",
				link: "/general/admin-dashboard",
			},
		],
	},
];
export const compactNavigation = defaultNavigation;
export const futuristicNavigation = defaultNavigation;
export const horizontalNavigation = defaultNavigation;
