/* tslint:disable:max-line-length */
import { FuseNavigationItem } from "@fuse/components/navigation";
import { random } from "lodash";

export const defaultNavigation: FuseNavigationItem[] = [
	{
		id: "landing",
		title: "Home",
		type: "basic",
		link: "/landing",
		icon: "heroicons_outline:home",
	},
	//ACM
	{
		id: "acm",
		title: "ACM",
		type: "collapsable",
		icon: "heroicons_outline:chip",

		children: [
			{
				id: "dashboard",
				title: "Dashboard",
				type: "basic",
				link: "/acm/acmdashboard",
				icon: "heroicons_outline:view-grid",
			},
			{
				id: "rule-book",
				title: "Rule Book",
				type: "collapsable",
				icon: "heroicons_outline:speakerphone",
				children: [
					{
						id: "rules",
						title: "Rules",
						type: "basic",
						link: "/acm/rule-book/rules",
						icon: "heroicons_outline:document-text",
					},
					{
						id: "risk",
						icon: "heroicons_outline:shield-exclamation",
						title: "Risk",
						type: "basic",
						link: "/acm/rule-book/risk",
					},
					{
						id: "variant",
						icon: "heroicons_outline:newspaper",
						title: "Variant",
						type: "collapsable",
						children: [
							{
								id: "risk",
								title: "Risk",
								type: "basic",
								icon: "heroicons_outline:folder-open",
								link: "/acm/rule-book/variant/risk",
							},
							{
								id: "rules",
								title: "Rules",
								icon: "heroicons_outline:folder-open",
								type: "basic",
								link: "/acm/rule-book/variant/rules",
							},
						],
					},
					{
						id: "import",
						icon: "heroicons_outline:save",
						title: "Import",
						type: "collapsable",
						children: [
							{
								id: "rules",
								title: "Import Rules",
								type: "basic",
								icon: "heroicons_outline:plus-sm",
								link: "/acm/rule-book/import/rules",
							},
							{
								id: "risk",
								title: "Import Risk",
								type: "basic",
								icon: "heroicons_outline:plus-sm",
								link: "/acm/rule-book/import/risk",
							},
						],
					},
					{
						id: "audit-logs",
						title: "Audit Logs",
						icon: "heroicons_outline:download",
						type: "collapsable",
						children: [
							{
								id: "rules",
								title: "Rules",
								icon: "heroicons_outline:folder-open",
								type: "basic",
								link: "/acm/rule-book/audit-logs/rules",
							},
							{
								id: "risk",
								title: "Risk",
								icon: "heroicons_outline:folder-open",
								type: "basic",
								link: "/acm/rule-book/audit-logs/risk",
							},
						],
					},
				],
			},
			{
				id: "master-data",
				title: "Master Data",
				type: "collapsable",
				icon: "heroicons_outline:database",
				children: [
					{
						id: "mitigations",
						title: "Mitigations",
						type: "collapsable",
						icon: "heroicons_outline:bookmark-alt",
						children: [
							{
								id: "mc-control",
								title: "MC Control",
								icon: "heroicons_outline:briefcase",
								type: "basic",
								link: "/acm/master-data/mitigations/mc-control",
							},
							{
								id: "upload",
								title: "Upload",
								icon: "heroicons_outline:cloud-upload",
								type: "basic",
								link: "/acm/master-data/mitigations/upload",
							},
						],
					},
					{
						id: "acm-owners",
						title: "ACM Owners",
						type: "basic",
						link: "/acm/master-data/acm-owners",
						icon: "heroicons_outline:archive",
					},
					{
						id: "rule-type",
						title: "Rule Type",
						type: "basic",
						link: "/acm/master-data/rule-type",
						icon: "heroicons_outline:document-text",
					},
					{
						id: "risk-type",
						title: "Risk Type",
						type: "basic",
						icon: "heroicons_outline:document-text",
						link: "/acm/master-data/risk-type",
					},
					{
						id: "business-process",
						title: "Business Processes",
						icon: "heroicons_outline:presentation-chart-line",
						type: "basic",
						link: "/acm/master-data/business-processes",
					},
					{
						id: "business-sub-process",
						title: "Business Sub Processes",
						type: "basic",
						icon: "heroicons_outline:presentation-chart-bar",
						link: "/acm/master-data/business-sub-processes",
					},
					{
						id: "org-field",
						title: "Org Field",
						icon: "heroicons_outline:globe-alt",
						type: "collapsable",
						children: [
							{
								id: "org-fields",
								title: "ORG Fields",
								type: "basic",
								icon: "heroicons_outline:plus-circle",
								link: "/acm/master-data/org-field/org-fields",
							},
							{
								id: "org-fields",
								title: "Download",
								type: "basic",
								icon: "heroicons_outline:download",
								link: "/acm/master-data/org-field/download",
							},
							{
								id: "org-fields",
								title: "Upload",
								type: "basic",
								icon: "heroicons_outline:cloud-upload",
								link: "/acm/master-data/org-field/upload",
							},
							{
								id: "org-names",
								title: "ORG Names",
								type: "basic",
								icon: "heroicons_outline:plus-circle",
								link: "/acm/master-data/org-field/org-names",
							},
							{
								id: "org-names",
								title: "ORG Names Variant",
								type: "basic",
								icon: "heroicons_outline:plus-circle",
								link: "/acm/master-data/org-field/org-names-variant",
							},
						],
					},
				],
			},
			{
				id: "rem",
				title: "REM",
				icon: "heroicons_outline:folder-open",
				type: "collapsable",
				children: [
					{
						id: "rem-config",
						title: "REM Config",
						icon: "heroicons_outline:plus",
						type: "basic",
						link: "/acm/rem/rem-config",
					},
					{
						id: "risk-schedule",
						title: "Risk Schedule",
						type: "basic",
						icon: "heroicons_outline:plus",
						link: "/acm/rem/risk-schedule",
					},
					{
						id: "tcode-sync",
						title: "Tcode Sync",
						type: "basic",
						link: "/acm/rem/tcode-sync",
						icon: "heroicons_outline:plus",
					},
				],
			},
			{
				id: "risk-analysis",
				title: "Risk Analysis",
				icon: "heroicons_outline:eye",
				type: "collapsable",
				children: [
					{
						id: "online",
						title: "Online",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/online/" + random(1, 100000),
					},
					{
						id: "offline",
						title: "Offline",
						icon: "heroicons_outline:folder-open",
						type: "collapsable",
						children: [
							{
								id: "import",
								icon: "heroicons_outline:folder-download",
								title: "Import",
								type: "basic",
								link: "/acm/risk-analysis/offline/import",
							},
							{
								id: "user-browser",
								title: "User Browser",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/user-browser",
							},
							{
								id: "user-variant",
								title: "User Variant",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/user-variant",
							},
							{
								id: "sod-analysis",
								title: "SoD Analysis",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/sod-analysis",
							},
							{
								id: "tasks",
								title: "Tasks",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/offline/tasks",
							},
						],
					},
					{
						id: "simulation",
						title: "Simulation",
						icon: "heroicons_outline:folder-open",
						type: "collapsable",
						children: [
							{
								id: "online",
								title: "Online",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/simulation/online",
							},
							{
								id: "offline",
								title: "Offilne",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/simulation/offline",
							},
						],
					},
					{
						id: "position-id",
						title: "Position Id",
						icon: "heroicons_outline:folder-open",
						type: "collapsable",
						children: [
							{
								id: "analyisis",
								title: "Analysis",
								icon: "heroicons_outline:folder-add",
								type: "basic",
								link: "/acm/risk-analysis/position-id/analyisis",
							},
							{
								id: "Logs",
								title: "logs",
								type: "basic",
								icon: "heroicons_outline:folder-add",
								link: "/acm/risk-analysis/position-id/logs",
							},
						],
					},
					{
						id: "impact-analsis",
						title: "Impact Analysis",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/impact-analysis",
					},
					{
						id: "cross-system-analysis",
						title: "Cross System Online",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/cross-system-analysis-online/" + random(1, 100000),
					},
					{
						id: "cross-system-analysis1",
						icon: "heroicons_outline:folder-open",
						title: "Cross System Offline",
						type: "basic",
						link: "/acm/risk-analysis/cross-system-analysis1-offline/" + random(1, 100000),
					},
					{
						id: "dashboard",
						title: "Dashboard",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/dashboard",
					},
					{
						id: "sfAnalysis",
						title: "Non-ABAP",
						icon: "heroicons_outline:folder-open",
						type: "basic",
						link: "/acm/risk-analysis/sfAnalysis/" + random(1, 100000),
					},
				],
			},
			{
				id: "reports",
				title: "Reports",
				icon: "heroicons_outline:clipboard-list",
				type: "collapsable",
				children: [
					{
						id: "sod-results",
						title: "SoD Results",
						type: "basic",
						icon: "heroicons_outline:clipboard-check",
						link: "/acm/reports/sod-results",
					},
					{
						id: "cross-system-analysis",
						title: "Cross Analysis Results",
						type: "basic",
						link: "/acm/reports/cross-system-analysis",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "org-analysis-dashboard",
						title: "ORG Analysis Dashboard",
						type: "basic",
						link: "/acm/reports/org-analysis-dashboard",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "org-level-analysis",
						title: "ORG Analysis Results",
						type: "basic",
						link: "/acm/reports/org-level-analysis",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "org-report",
						title: "ORG Report",
						type: "basic",
						link: "/acm/reports/org-report",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "mitigation-report",
						title: "Mitigation Report",
						type: "basic",
						link: "/acm/reports/mitigation-report",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "risk-report",
						title: "Risk Report",
						type: "basic",
						link: "/acm/reports/risk-report",
						icon: "heroicons_outline:clipboard-check",
					},
					// {
					//   id: 'user-report',
					//   title: 'User Report',
					//   type: 'basic',
					//   link: '/acm/reports/user-report',
					//   icon: 'heroicons_outline:clipboard-check',
					// },
					{
						id: "risk-execution",
						title: "Risk Execution",
						type: "basic",
						link: "/acm/reports/risk-execution",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "rule-execution",
						title: "Rule Execution",
						type: "basic",
						link: "/acm/reports/rule-execution",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "tcode-execution",
						title: "Tcode Execution",
						type: "basic",
						link: "/acm/reports/tcode-execution",
						icon: "heroicons_outline:clipboard-check",
					},
					{
						id: "risk-exe-execution",
						title: "Risk Exe Summary",
						type: "basic",
						link: "/acm/reports/risk-exe-summary",
						icon: "heroicons_outline:clipboard-check",
					},

					{
						id: "rem-dashboard",
						title: "REM Dashboard",
						type: "basic",
						link: "/acm/reports/rem-dashboard",
						icon: "heroicons_outline:clipboard-check",
					},
				],
			},
		],
	},
];
export const compactNavigation = defaultNavigation;
export const futuristicNavigation = defaultNavigation;
export const horizontalNavigation = defaultNavigation;
